-- air_data.air_data_source definition
CREATE DATABASE  IF NOT EXISTS "air_data" /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
CREATE TABLE "air_data"."air_data_source" (
  "id" int NOT NULL AUTO_INCREMENT COMMENT '主键',
  "airlineLogo" varchar(100) DEFAULT NULL,
  "airlineShortCompany" varchar(100) DEFAULT NULL,
  "arrActCross" varchar(100) DEFAULT NULL,
  "arrActTime" varchar(100) DEFAULT NULL,
  "arrAirport" varchar(100) DEFAULT NULL,
  "arrCode" varchar(100) DEFAULT NULL,
  "arrOntimeRate" varchar(100) DEFAULT NULL,
  "arrPlanCross" varchar(100) DEFAULT NULL,
  "arrPlanTime" varchar(100) DEFAULT NULL,
  "arrTerminal" varchar(100) DEFAULT NULL,
  "checkInTable" varchar(100) DEFAULT NULL,
  "checkInTableWidth" varchar(100) DEFAULT NULL,
  "depActCross" varchar(100) DEFAULT NULL,
  "depActTime" varchar(100) DEFAULT NULL,
  "depAirport" varchar(100) DEFAULT NULL,
  "depCode" varchar(100) DEFAULT NULL,
  "depPlanCross" varchar(100) DEFAULT NULL,
  "depPlanTime" varchar(100) DEFAULT NULL,
  "depTerminal" varchar(100) DEFAULT NULL,
  "flightNo" varchar(100) DEFAULT NULL,
  "flightState" varchar(100) DEFAULT NULL,
  "localDate" varchar(100) DEFAULT NULL,
  "mainFlightNo" varchar(100) DEFAULT NULL,
  "shareFlag" varchar(100) DEFAULT NULL,
  "stateColor" varchar(100) DEFAULT NULL,
  PRIMARY KEY ("id")
) ENGINE=InnoDB AUTO_INCREMENT=149 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='航空数据原始表';